name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore WebUI/
    - name: Build
      run: dotnet build WebUI/ --configuration Release --no-restore

    - name: publish
      run: dotnet publish WebUI --configuration Release -o ./publish
    - name: deploy
      uses: azure/webapps-deploy@v2
      with: 
        app-name: NameDadJokes # Replace with your app name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package: ./publish
